apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
        - name: app
          image: ghcr.io/emanuelfrn/conv-temp:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: conv-temp
spec:
  type: NodePort
  selector:
    app: conv-temp
  ports:
    - port: 8080
      nodePort: 30000